"""initial schema

Revision ID: 9e449828dbcf
Revises: 
Create Date: 2026-02-07 05:09:34.163695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e449828dbcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_leaderboards_huggingface_url', table_name='ai_leaderboards')
    op.drop_index('ix_ai_leaderboards_id', table_name='ai_leaderboards')
    op.drop_index('ix_ai_leaderboards_model_name', table_name='ai_leaderboards')
    op.drop_table('ai_leaderboards')
    op.drop_index('ix_ai_startups_company_name', table_name='ai_startups')
    op.drop_index('ix_ai_startups_id', table_name='ai_startups')
    op.drop_index('ix_ai_startups_website', table_name='ai_startups')
    op.drop_table('ai_startups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_startups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('funding_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('funding_series', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('funding_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('founders', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('investors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry_tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_trending', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_startups_pkey')
    )
    op.create_index('ix_ai_startups_website', 'ai_startups', ['website'], unique=True)
    op.create_index('ix_ai_startups_id', 'ai_startups', ['id'], unique=False)
    op.create_index('ix_ai_startups_company_name', 'ai_startups', ['company_name'], unique=True)
    op.create_table('ai_leaderboards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('leaderboard_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('huggingface_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paper_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('benchmark_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_trending', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_leaderboards_pkey')
    )
    op.create_index('ix_ai_leaderboards_model_name', 'ai_leaderboards', ['model_name'], unique=False)
    op.create_index('ix_ai_leaderboards_id', 'ai_leaderboards', ['id'], unique=False)
    op.create_index('ix_ai_leaderboards_huggingface_url', 'ai_leaderboards', ['huggingface_url'], unique=True)
    # ### end Alembic commands ###
