"""YouTube 채널 시드 데이터 - AI 트렌드 유튜버 30명"""

# 해외 AI 유튜버 채널 (20명)
INTERNATIONAL_CHANNELS = [
    {
        "channel_id": "UCbfYPyITQ-7l4upoX8nvctg",
        "channel_name": "Two Minute Papers",
        "channel_handle": "@TwoMinutePapers",
        "description": "최신 AI 및 머신러닝 연구를 몇 분짜리 영상으로 쉽게 풀어주는 채널",
        "category": "해외",
        "priority": 10,
    },
    {
        "channel_id": "UCgRvm5a1Eh09ZRjW_WuDOPg",
        "channel_name": "DeepLearning.AI",
        "channel_handle": "@Deeplearningai",
        "description": "Andrew Ng이 이끄는 ML 교육 채널, 최신 기술 동향과 경력 개발",
        "category": "해외",
        "priority": 10,
    },
    {
        "channel_id": "UCfzlCWGWYyIQ0aLC5w48gBQ",
        "channel_name": "Sentdex",
        "channel_handle": "@sentdex",
        "description": "Python, 머신러닝, 딥러닝 실전 튜토리얼",
        "category": "해외",
        "priority": 9,
    },
    {
        "channel_id": "UC8butISFwT-Wl7EV0hUK0BQ",
        "channel_name": "freeCodeCamp.org",
        "channel_handle": "@freecodecamp",
        "description": "무료 코딩 교육, AI/ML 강좌 포함",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UCYO_jab_esuFRV4b17AJtAw",
        "channel_name": "3Blue1Brown",
        "channel_handle": "@3blue1brown",
        "description": "수학과 AI 개념을 시각적으로 설명",
        "category": "해외",
        "priority": 9,
    },
    {
        "channel_id": "UCkw4JCwteGrDHIsyIIKo4tQ",
        "channel_name": "Yannic Kilcher",
        "channel_handle": "@YannicKilcher",
        "description": "최신 ML 논문 리뷰와 뉴스",
        "category": "해외",
        "priority": 9,
    },
    {
        "channel_id": "UCBJycsmduvYEL83R_U4JriQ",
        "channel_name": "Marques Brownlee",
        "channel_handle": "@mkbhd",
        "description": "기술 리뷰, AI 제품 소개",
        "category": "해외",
        "priority": 7,
    },
    {
        "channel_id": "UCh9nVJoWXmFb7sLApWGcLPQ",
        "channel_name": "Codebasics",
        "channel_handle": "@codebasics",
        "description": "데이터 사이언스, ML 튜토리얼",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UCW5YeuERMmlnqo4oq8vwUpg",
        "channel_name": "The AI Advantage",
        "channel_handle": "@aiadvantage",
        "description": "AI 도구 활용법, 워크플로 자동화",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UCR-DXc1voovS8nhAvccRZhg",
        "channel_name": "Jeff Su",
        "channel_handle": "@JeffSu",
        "description": "AI 생산성 도구 활용",
        "category": "해외",
        "priority": 7,
    },
    {
        "channel_id": "UCdyjiB5H8Pu7aDTNVXTTpcg",
        "channel_name": "Wes Roth",
        "channel_handle": "@WesRoth",
        "description": "AI 업계 뉴스와 해설",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UC295-Dw_tDNtZXFeAPAW6Aw",
        "channel_name": "Matt Wolfe",
        "channel_handle": "@mreflow",
        "description": "최신 AI 도구 리뷰",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UCTTaKL5fOjUx8a9mr6Yy29g",
        "channel_name": "MattVidPro AI",
        "channel_handle": "@MattVidPro",
        "description": "AI 활용 창의적 콘텐츠",
        "category": "해외",
        "priority": 7,
    },
    {
        "channel_id": "UCUzGoe3mbN7dkQOXQd8XPqw",
        "channel_name": "Matthew Berman",
        "channel_handle": "@matthew_berman",
        "description": "최신 AI 기술 분석과 모델 비교",
        "category": "해외",
        "priority": 8,
    },
    {
        "channel_id": "UCS9OE6KeXQ54nSMqhRx0_EQ",
        "channel_name": "All About AI",
        "channel_handle": "@AllAboutAI",
        "description": "AI 발전의 실질적 의미 분석",
        "category": "해외",
        "priority": 7,
    },
    {
        "channel_id": "UCpW9uFgucVTZUc68yQIs0Zw",
        "channel_name": "Siraj Raval",
        "channel_handle": "@SirajRaval",
        "description": "재미있는 ML 튜토리얼",
        "category": "해외",
        "priority": 6,
    },
    {
        "channel_id": "UCLbS7oE35BxS2NpQu5Fsz3Q",
        "channel_name": "Liam Ottley",
        "channel_handle": "@LiamOttley",
        "description": "AI 비즈니스 자동화 전략",
        "category": "해외",
        "priority": 7,
    },
    {
        "channel_id": "UC-b3c7kxa5vU-bnmaROgvog",
        "channel_name": "AI Explained",
        "channel_handle": "@aiexplained-official",
        "description": "최신 AI 개발 동향과 모델 출시",
        "category": "해외",
        "priority": 9,
    },
    {
        "channel_id": "UCUfJC5IaAy4C_LD6W8GAYPw",
        "channel_name": "Curious Refuge",
        "channel_handle": "@curiousrefuge",
        "description": "AI 활용 영화 제작",
        "category": "해외",
        "priority": 6,
    },
    {
        "channel_id": "UCdOMoNOC-8k4z0pPQB26VEA",
        "channel_name": "Future Tech Pilot",
        "channel_handle": "@FutureTechPilot",
        "description": "시각·미디어 분야 AI 활용",
        "category": "해외",
        "priority": 6,
    },
]

# 국내 AI 유튜버 채널 (10명)
KOREAN_CHANNELS = [
    {
        "channel_id": "UCKNLe33F3cU3NLLMiY8F7aA",
        "channel_name": "유튜브신쌤",
        "channel_handle": "@youtube_teacher",
        "description": "AI 입문자를 위한 친절한 강의",
        "category": "국내",
        "priority": 9,
    },
    {
        "channel_id": "UC_dHrvEKALRxBWmVpHjCqGQ",
        "channel_name": "일잘러 장피엠",
        "channel_handle": "@jangpm",
        "description": "ChatGPT 업무 생산성 향상 팁",
        "category": "국내",
        "priority": 9,
    },
    {
        "channel_id": "UCt2wAAXgm87ACiQnDHQEW6Q",
        "channel_name": "알린 ALINN",
        "channel_handle": "@ALINN_official",
        "description": "AI로 업무 능률 높이기",
        "category": "국내",
        "priority": 8,
    },
    {
        "channel_id": "UCemzZ0J4mPcRlkzlb5_xeRw",
        "channel_name": "시민개발자 구씨",
        "channel_handle": "@citizendeveloper",
        "description": "AI 노코드 활용법",
        "category": "국내",
        "priority": 8,
    },
    {
        "channel_id": "UCCzXFyP4V21EpUUfWmDWdUg",
        "channel_name": "AI 알려주는 남자 (데브남)",
        "channel_handle": "@devnam",
        "description": "ChatGPT 활용법 전문",
        "category": "국내",
        "priority": 8,
    },
    {
        "channel_id": "UCiF6i7_lwNVdVRwX4Z2nFLg",
        "channel_name": "행글라이터",
        "channel_handle": "@hangwriter",
        "description": "AI로 콘텐츠 만들기",
        "category": "국내",
        "priority": 7,
    },
    {
        "channel_id": "UC6ESkDCNXmQQUPBh_6JHPJA",
        "channel_name": "평범한 사업가",
        "channel_handle": "@ordinarybusinessman",
        "description": "해외 AI 소식 한글 자막, 전문가 인터뷰",
        "category": "국내",
        "priority": 8,
    },
    {
        "channel_id": "UCLWr_lJIUuIJZoXZMy0KQMA",
        "channel_name": "감자나라AI",
        "channel_handle": "@potatocountryai",
        "description": "ChatGPT 중심 AI 활용 후기",
        "category": "국내",
        "priority": 7,
    },
    {
        "channel_id": "UCgWJMI7LXCWPkN7LjQgW0qQ",
        "channel_name": "김그륜",
        "channel_handle": "@kimgroon",
        "description": "할리우드 영상 디자이너의 AI 활용",
        "category": "국내",
        "priority": 8,
    },
    {
        "channel_id": "UC7NhKCRzBpPWqLBn4y76f4w",
        "channel_name": "기묘한 자동화",
        "channel_handle": "@strangeautomation",
        "description": "AI 업무 자동화 및 수익화",
        "category": "국내",
        "priority": 8,
    },
]

# 전체 채널 리스트
ALL_CHANNELS = INTERNATIONAL_CHANNELS + KOREAN_CHANNELS
